pygments: true
permalink: /:categories/:title
auto: true
# url: /fala-api-doc
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
